export type ProjectVisual = {
  slug: string;
  compositionId: `Project-${string}`;
  title: string;
  eyebrow: string;
  summary: string;
  cover: `/images/projects/${string}`;
  workflow: readonly string[];
  architecture: readonly string[];
  outcomes: readonly string[];
  accent: string;
};

export const projectVisuals = [
  {
    slug: "agents-fun-eliza",
    compositionId: "Project-agents-fun-eliza",
    title: "agents-fun-eliza",
    eyebrow: "Autonomous conversational agent",
    summary: "Context-aware agent loops across intent, memory, reasoning, tools, and learning.",
    cover: "/images/projects/agents-fun-eliza/cover.jpg",
    workflow: [
      "Message intake",
      "Intent and context",
      "Memory retrieval",
      "Tool routing",
      "Response learning",
    ],
    architecture: ["Perception", "Memory", "Reasoning", "Actions"],
    outcomes: ["Autonomous conversations", "Persistent memory", "Tool orchestration"],
    accent: "#3ecfbd",
  },
  {
    slug: "ai-prediction-market-trader",
    compositionId: "Project-ai-prediction-market-trader",
    title: "AI Prediction Market Trader",
    eyebrow: "Autonomous DeFi trading agent",
    summary: "Market, sentiment, and risk signals flow into model-backed execution decisions.",
    cover: "/images/projects/trader/cover.jpg",
    workflow: [
      "Market intake",
      "Signal features",
      "Ensemble forecast",
      "Risk sizing",
      "Web3 execution",
    ],
    architecture: ["Data collectors", "ML scoring", "Risk engine", "Execution adapter"],
    outcomes: ["Confidence-gated trades", "Drawdown control", "Performance reporting"],
    accent: "#7ed957",
  },
  {
    slug: "automl-platform",
    compositionId: "Project-automl-platform",
    title: "End-to-End AutoML Platform",
    eyebrow: "MLOps lifecycle automation",
    summary: "A repeatable pipeline for tracking, tuning, deploying, and monitoring models.",
    cover: "/images/projects/automl/cover-01.jpg",
    workflow: [
      "Data validation",
      "Feature pipeline",
      "Hyperparameter search",
      "Model registry",
      "Drift retraining",
    ],
    architecture: ["Orchestration", "Experiments", "Serving", "Observability"],
    outcomes: ["100+ hours saved monthly", "70% workload reduction", "Auditable releases"],
    accent: "#f5b84b",
  },
  {
    slug: "genie-cli",
    compositionId: "Project-genie-cli",
    title: "genie-cli",
    eyebrow: "LLM-powered agent scaffolding",
    summary: "A command-line workflow that turns natural language into deployable agent projects.",
    cover: "/images/projects/genie-cli/cover.jpg",
    workflow: [
      "Prompt brief",
      "Template match",
      "LLM planning",
      "Scaffold files",
      "Deployment handoff",
    ],
    architecture: ["CLI shell", "Prompt engine", "Template library", "Generated project"],
    outcomes: ["Faster prototypes", "Production defaults", "Extensible templates"],
    accent: "#42b883",
  },
  {
    slug: "genie-code-generation",
    compositionId: "Project-genie-code-generation",
    title: "Genie Code Generation Platform",
    eyebrow: "Natural language to agent systems",
    summary: "Requirements become behavior specs, FSMs, code, tests, and deployable packages.",
    cover: "/images/projects/genie/cover-01.jpg",
    workflow: [
      "Natural language",
      "Semantic planning",
      "FSM synthesis",
      "Code validation",
      "Agent deployment",
    ],
    architecture: ["Prompt pipeline", "Scaffolding engine", "Validation gates", "MLOps release"],
    outcomes: ["Weeks to minutes", "Generated tests", "Agent democratization"],
    accent: "#3ea7ff",
  },
  {
    slug: "gitaura",
    compositionId: "Project-gitaura",
    title: "GitAura",
    eyebrow: "Developer profile analytics",
    summary: "Contribution activity is converted into scores, achievements, and leaderboard views.",
    cover: "/images/projects/gitaura/cover.jpg",
    workflow: [
      "Profile ingest",
      "Contribution graph",
      "Aura scoring",
      "Achievements",
      "Leaderboard view",
    ],
    architecture: ["Data fetcher", "Score engine", "Visualization layer", "Profile surface"],
    outcomes: ["Clear profile signal", "Achievement badges", "Ranked comparisons"],
    accent: "#8bd450",
  },
  {
    slug: "plugin-memeooorr",
    compositionId: "Project-plugin-memeooorr",
    title: "plugin-memeooorr",
    eyebrow: "Meme-aware agent plugin",
    summary: "A plugin pipeline for meme understanding, generation, trend scoring, and safety.",
    cover: "/images/projects/plugin-memeooorr/cover.jpg",
    workflow: [
      "Trend intake",
      "Vision analysis",
      "Template match",
      "Caption generation",
      "Safety scoring",
    ],
    architecture: ["Core plugin", "Vision adapter", "Template store", "Analytics layer"],
    outcomes: ["Cultural context", "Safer publishing", "Agent engagement"],
    accent: "#ff7a59",
  },
  {
    slug: "rag-chatbot-oil-gas",
    compositionId: "Project-rag-chatbot-oil-gas",
    title: "Oil & Gas RAG Chatbot",
    eyebrow: "Field-ready knowledge retrieval",
    summary: "Technical documents become cited, conversational answers for field engineers.",
    cover: "/images/projects/rag-chatbot/cover-01.jpg",
    workflow: [
      "Document ingest",
      "Chunk embeddings",
      "Vector search",
      "Answer synthesis",
      "Source citation",
    ],
    architecture: ["ETL pipeline", "Vector database", "LLM gateway", "Access control"],
    outcomes: ["Cited answers", "Faster field lookup", "Fresh knowledge base"],
    accent: "#2dd4bf",
  },
  {
    slug: "text2sql-agent",
    compositionId: "Project-text2sql-agent",
    title: "Text2SQL2Plot Agent",
    eyebrow: "Industrial natural-language analytics",
    summary: "Field questions become validated SQL, charts, and operational diagnostics.",
    cover: "/images/projects/text2sql/cover-01.jpg",
    workflow: [
      "Natural query",
      "Schema context",
      "SQL generation",
      "Query validation",
      "Chart insight",
    ],
    architecture: ["LLM translator", "SQL validator", "Time-series store", "Plot generator"],
    outcomes: ["20% repair-time reduction", "Lower SQL dependence", "Audit trail"],
    accent: "#38bdf8",
  },
  {
    slug: "text2sql2plot",
    compositionId: "Project-text2sql2plot",
    title: "Text2SQL2Plot",
    eyebrow: "Turbomachinery analytics workflow",
    summary: "Sensor-data questions flow through SQL generation into diagnostic visualizations.",
    cover: "/images/projects/text2sql2plot/cover.jpg",
    workflow: [
      "Field question",
      "Intent parsing",
      "SQL builder",
      "Timescale query",
      "Diagnostic plot",
    ],
    architecture: ["Domain context", "Query engine", "Result processor", "Insight surface"],
    outcomes: ["85% query accuracy", "15 facilities", "Transparent SQL"],
    accent: "#f59e0b",
  },
  {
    slug: "turbomachinery-failure-prediction",
    compositionId: "Project-turbomachinery-failure-prediction",
    title: "Turbomachinery Failure Prediction",
    eyebrow: "Predictive maintenance model",
    summary: "Sensor streams become explainable failure risk scores and maintenance actions.",
    cover: "/images/projects/turbomachinery/cover-01.jpg",
    workflow: [
      "Sensor streams",
      "Feature windows",
      "Ensemble model",
      "Risk scoring",
      "Maintenance alert",
    ],
    architecture: ["Signal pipeline", "Feature store", "Prediction service", "Alert router"],
    outcomes: ["96.5% accuracy", "7-30 day warning", "Explainable predictions"],
    accent: "#ef6f6c",
  },
] as const satisfies readonly ProjectVisual[];
